hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    n_trials: 9
    n_jobs: 1
    params:
      primary_optimizer: choice(adamuon,muon,adamw)
      rope_implementation: choice(custom,torch_builtin,none)

