program: src/scaletraining/entrypoints/train.py
method: grid
metric:
  name: train_per_token_loss
  goal: minimize
parameters:
  primary_optimizer:
    values: [adamuon, muon, adamw]
  rope_implementation:
    values: [custom, torch_builtin, none]
