_wandb:
    value:
        cli_version: 0.21.1
        e:
            kdm4l41djtkujxgsgy0ylc47w80jhudf:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 20
                cpu_count_logical: 20
                disk:
                    /:
                        total: "927751548928"
                        used: "106293788672"
                email: jasondpett@gmail.com
                executable: /home/j/miniconda3/envs/j/bin/python
                git:
                    commit: fb205cae65f1439574f0e89c5976fd486d7bee56
                    remote: git@github.com:jasonp02/ScaleTraining.git
                gpu: Radeon RX 7900 XTX
                gpu_amd:
                    - id: "0"
                      maxPower: "327.0"
                      model: "0x744c"
                      performanceLevel: auto
                      series: Radeon RX 7900 XTX
                      sku: 31XFSHBS1
                      uniqueId: "0x7fddfa0059142255"
                      vbiosVersion: 113-31XFSHBS1-L03
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 1
                host: j
                memory:
                    total: "33345146880"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/j/Projects/ScaleTraining/main.py
                python: CPython 3.10.18
                root: /home/j/Projects/ScaleTraining
                startedAt: "2025-08-28T00:33:19.879887Z"
                writerId: kdm4l41djtkujxgsgy0ylc47w80jhudf
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
            "2":
                - 1
                - 11
                - 49
                - 51
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.4
            "12": 0.21.1
            "13": linux-x86_64
