defaults:
  - _self_
  - train
  - model
  - optimizer
  - tokenizer
  - logging
  - generation
  - paths
  - moe
  # generation config is optional; kept separate for tooling that composes it explicitly
  - override hydra/sweeper: grid

hydra:
  run:
    dir: .
  sweep:
    dir: multirun
    subdir: ${hydra.job.num}

# Core knobs now live in single files so each concern stays isolated.
