defaults:
  - _self_
  # Namespaced groups: transformer, tokenizer, logging, moe
  - transformer: default  # Must be present for eval_datasets to be available in run_evals.py
  - tokenizer: default
  - logging: default
  - moe: default
  # Hydra sweeper config
  - override hydra/sweeper: grid

hydra:
  run:
    dir: .
  sweep:
    dir: multirun
    subdir: ${hydra.job.num}

# Composes only groups; all knobs live under transformer/, tokenizer/, logging/.
