defaults:
  - _self_
  # Namespaced groups: model, tokenizer, logging
  - model: default
  - tokenizer: default
  - logging: default
  # Hydra sweeper config
  - override hydra/sweeper: grid

hydra:
  run:
    dir: .
  sweep:
    dir: multirun
    subdir: ${hydra.job.num}

# Composes only groups; all knobs live under model/, tokenizer/, logging/.
