defaults:
  - device: default
  - training: default
  - model: default
  - optimizer: default
  - tokenizer: default
  - logging: default
  - generation: default
  - paths: default
  - moe: default
  - override hydra/sweeper: grid
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: multirun
    subdir: ${hydra.job.num}

# Core knobs now live in single files so each concern stays isolated.
