defaults:
  - _self_
  - transformer
  - tokenizer
  - logging
  - moe
  - paths
  - override hydra/sweeper: grid

hydra:
  run:
    dir: .
  sweep:
    dir: multirun
    subdir: ${hydra.job.num}

# Core knobs now live in single files (transformer, tokenizer, logging, moe, paths).
