# @package _global_
hydra:
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params:
      model.lr: 0.1, 0.07, 0.03, 0.025, 0.01, 0.005
  sweep:
    subdir: ${sweep.name}/${now:%Y-%m-%d_%H-%M-%S}/${hydra.job.num}

sweep:
  # Override via `+sweep.name=my_sweep`
  name: grid
